name: Fetch scores

on: workflow_dispatch

jobs:
  fetch:
    runs-on: ubuntu-latest  # Replace with your desired OS if needed 

    steps:
      - uses: actions/checkout@v3  # Check out your repository code

      # Add steps to run your Python script below
      - name: Run Python Script
        run: python fetch-sales-point.py  
